# OllamaLinux partition module configuration

efiSystemPartition:      "/boot/efi"
efiSystemPartitionSize:  300
efiSystemPartitionName:  EFI

userSwapChoices:
    - none
    - small
    - suspend
    - file

drawNestedPartitions:    false

alwaysShowPartitionLabels: true

initialPartitioningChoice: erase

initialSwapChoice: none

defaultFileSystemType:   "ext4"

availableFileSystemTypes: ["ext4", "btrfs", "xfs"]
