# OllamaLinux users module configuration

defaultGroups:
    - name: users
      state: must-exist
    - name: lp
      state: must-exist
    - name: video
      state: must-exist
    - name: network
      state: must-exist
    - name: storage
      state: must-exist
    - name: wheel
      state: create-if-absent
    - name: sudo
      state: create-if-absent

autologinGroup:  autologin

doAutologin:     false

sudoersGroup:    sudo

setRootPassword: true

doReusePassword: true

passwordRequirements:
    minLength: 6
    maxLength: -1
    libpwquality:
        - minlen=6

userShell: /bin/bash

avatarFilePath: ~/.face
