# OllamaLinux welcome module configuration

showSupportUrl:          true
showKnownIssuesUrl:      true
showReleaseNotesUrl:     false

requirements:
    requiredStorage:    20.0
    requiredRam:        2.0
    internetCheckUrl:   https://cloudflare.com
    check:
        - storage
        - ram
        - power
        - internet
    required:
        - storage
        - ram
